import {
  Type,
  Hash,
  CheckSquare,
  ChevronDown,
  List,
  Calendar,
  Link2,
  AtSign,
  DollarSign,
  Phone,
  Star,
  Percent,
  AlignLeft,
  Paperclip,
  ExternalLink,
  Search,
  Calculator,
} from 'lucide-react';
import type { TableFieldType } from '@atlas-platform/shared';

export const FIELD_TYPE_ICONS: Record<TableFieldType, React.ComponentType<{ size?: number }>> = {
  text: Type,
  number: Hash,
  checkbox: CheckSquare,
  singleSelect: ChevronDown,
  multiSelect: List,
  date: Calendar,
  url: Link2,
  email: AtSign,
  currency: DollarSign,
  phone: Phone,
  rating: Star,
  percent: Percent,
  longText: AlignLeft,
  attachment: Paperclip,
  linkedRecord: ExternalLink,
  lookup: Search,
  rollup: Calculator,
};
